version: "3.9"

services:
  api:
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_HOST_PATH=/usr/share/dotnet/dotnet
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_NOLOGO=true
    volumes:
      - ../src/ProjectManagement.Api:/app/src/ProjectManagement.Api:cached
      - ../src/ProjectManagement.Application:/app/src/ProjectManagement.Application:cached
      - ../src/ProjectManagement.Domain:/app/src/ProjectManagement.Domain:cached
      - ../src/ProjectManagement.Infrastructure:/app/src/ProjectManagement.Infrastructure:cached
      - ../tests:/app/tests:cached
    command: ["dotnet", "watch", "run", "--urls", "http://+:5000"]

  db:
    environment:
      - MSSQL_DB=${MSSQL_DB:-ProjectManagementDb}
