version: "3.9"

services:
  api:
    build:
      context:  ..
      dockerfile: Dockerfile
    container_name: projectmanagement_api
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ../src/ProjectManagement.Api:/src/ProjectManagement.Api:cached

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: projectmanagement_db
    ports:
      - "${MSSQL_PORT:-1433}:1433"
    environment:
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./sqlserver-init:/docker-entrypoint-initdb.d

volumes:
  sqlserver_data:
